### ISSUE TITLE
tftp conntrack not working with firehol v3

### ISSUE THREAD

**Issue by hcouplet** [ktsaou/firehol#80]
I am using firehol & fireqos and I have an issue with a firehol configuration when it's activated with latest firehol v3 from git.
When activating the same config with v2 version it works well.

I can reproduce this and check that a program that is using tftp over nat is not working correctly when having v3 firehol activated.
I think that there is the some issue ftp conntrack.

As v3 has a faster activation and has ipset, I would rather keep v3.

Can you help me on this ?

**Comment by philwhineray** [comment]
Strange, I can't think of anything that should affect this.

Could you create a minimal config to show the problem first - we may need to use it a few times.

Then run v3 with this at the top:

~~~~
FIREHOL_FAST_ACTIVATION=0
~~~~

If it still doesn't work, then run each version and attach the resultant iptables rules and modules:

~~~~
firehol status > iptables.txt
lsmod | grep nf_ > modules.txt
~~~~

**Comment by hcouplet** [comment]
Hi,
Thanks for your help.

I made up a simplified configuration and tried the FIREHOL_FAST_ACTIVATION=0 option but It didn't helped.

I ran both version and got the iptables.txt and modules.txt files as requested.
I also took a tcpdump trace on both interface on the firehol router. (.pcap file that you can open with wireshark).

Client software is using IP 172.25.25.30 and connect to 172.27.8.2.
Client use a vpn tunnel to the Firehol router.
firehol router has tun26 interface (172.26.0.30) and br1 interface (172.27.8.1).
So packet from client software to 172.27.8.2 goes through interface tun26 to br1 on the firehol router.

You will find all the files in http://couplet.be/temp/firehol_debug.zip

Please tell me if I can do anything else.

**Comment by philwhineray** [comment]
Looking at dump_br1_V3.pcap it seems as though packet 5 is being blocked (it is missing from the tun26 dump): inface br1, outface tun26, source port 6230 dest port 61040.

I think the difference is down to either stricter helper matching in v3 (probable) or stricter matching of invalid packets (as far as the connection tracker is concerned - I don't think this is likely though). The dropped packet should be logged; can you find the complete log entry for it? I think it should be labelled "OUT-c1config" or "INVALID PASS" respectively.

Have you always used "all" for your rule? The stricter matching in v3 does not include the tftp helper in the "all" case by the look of it, which would account for the difference.

You could create an explicit tftp rule or try adding to the helper_all=... line in the firehol script to see if that resolves it.

**Comment by ktsaou** [comment]
I have removed tftp from the `all` service because I found notes about attackers being able to confuse the kernel connection tracker helpers and establish connections they should not be allowed to. According to the netfilter devs, connection tracker helpers should only by used with CT actions in the raw table (`cthelper` in firehol). These rules instruct the connection helpers about the trustworthy side of the communication.

Check this: https://home.regit.org/netfilter-en/secure-use-of-helpers/

In v3 there is the option `FIREHOL_CONNTRACK_HELPERS_ASSIGNMENT` which by default is set to `kernel` to emulate v2 behavior (the least secure though). If set to `firehol`, firehol will add CT rules automatically. Unfortunately this code in unaware of NAT and therefore cannot be used as the default option. The most secure option is `manual` where the admin is expected the configure the trustworthy side of the communication using the firehol `cthelper` command.

So, to emulate as much as possible of v2 functionality, I only included helpers that are commonly used in internet traffic. `tftp` is one of those I removed, since there is no meaning to run `tftp` on the internet.

I suggest to add `server tftp accept` or `client tftp accept` when `tftp` is needed, or use `cthelper` to let the kernel know where to look for packets it can trust.

**Comment by hcouplet** [comment]
I don't see log entry when it's not working.
Adding the tftp helper in helper_all works.

I will use "any" instead of "all" and use FIREHOL_CONNTRACK_HELPERS_ASSIGNMENT=manual to switch to cthelper as you recommended.

I looked for documentation on cthelper but didn't find it.  I also didn't found documentation on the mailing list too. Do you have an example or a starting point ?

Anyway thanks for your help and your helpful support.

Regards,
Hervé

**Comment by ktsaou** [comment]
Added new issue #94 to add cthelper docs
